#!/usr/bin/env sh
#MISE description="Add default tasks for a Python project with uv and pytest"
#MISE dir="{{cwd}}"

mise tasks add "install" \
    --description "Install dependencies" \
    --alias "i" \
    -- uv sync

mise tasks add "test" \
    --description "Run tests" \
    --alias "t" \
    -- uv run pytest
