#!/usr/bin/env sh
#MISE description="Initialize a Python project with uv and pytest"
#MISE dir="{{cwd}}"

mise use usage uv
mise lock
uv init
uv add pytest

mise config set "settings.python.uv_venv_auto" "true"
