[[mgr.prepend_keymap]]
on = ["g", "?"]
run = "help"

[[mgr.prepend_keymap]]
on = ["~"]
run = "noop"

[[mgr.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "cd to root of Git repo"
