[tools]
bun = "latest"
jq = "latest"

[hooks]
postinstall = "bun install"

[tasks.generate]
alias = ["gen", "g"]
depends = ["docs:generate", "mise:generate-docs", "coreutils:generate"]

[tasks."docs:dev"]
alias = "docs:b"
run = "bun run docs:dev"

[tasks."docs:build"]
alias = "docs:b"
run = "bun run docs:build"

[tasks."docs:generate"]
alias = ["docs:g", "docs:update", "docs:up"]
depends = ["mise:generate-docs", "devbox:generate-docs"]

[tasks."mise:generate-docs"]
alias = "mise:update-docs"
run = """
mise generate task-docs --cd "$HOME" >docs/mise_global_tasks.md
"""

[settings]
experimental = true
lockfile = true
