#!/usr/bin/env bash
#MISE description="Scaffold a Python project with uv and pytest"
#MISE dir="{{cwd}}"
#USAGE flag "--commit" help="Commit changes after scaffolding"

mise run python:init
mise run python:tasks-add

if [ "$usage_commit" = "true" ]; then
    git add -A
    git commit -m "build: Scaffold Python project with uv and pytest"
fi
