#!/usr/bin/env bash
#MISE description="Reinstall Neovim plugins"

echo '[dotfiles][nvim] Reinstalling plugins...'
rm -rf ~/.config/nvimiw/ ~/.local/share/nvim/
rm ~/.config/nvim/lazy-lock.json
nvim --headless "+Lazy! install" +qa
