[".config/jjui/themes/base16-solarized-dark.toml"]
type = "file"
url = "https://raw.githubusercontent.com/vic/tinted-jjui/main/themes/base16-solarized-dark.toml"
refreshPeriod = "168h"
readonly = true

