[tools]
"devbox:exiftool" = "latest"
"devbox:taskwarrior" = "latest"
"devbox:timewarrior" = "latest"
"devbox:gpg-tui" = "latest"
"devbox:renameutils" = "latest"
"devbox:poppler-utils" = "latest"
"devbox:git-extras" = "latest"
"devbox:git" = "latest"
"devbox:file" = "latest"
"devbox:readline" = "latest"
"devbox:ffmpeg" = "latest"
