[plugins]
devbox = "https://github.com/jbadeau/mise-nix.git"

[tools]
"aqua:dlvhdr/gh-dash" = "latest"
"aqua:jorgerojas26/lazysql" = "latest"
"aqua:zk-org/zk" = "latest"
bat = "latest"
bottom = "latest"
cargo-binstall = "latest"
chezmoi = "latest"
coreutils = "latest"
dua = "latest"
duf = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glab = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
"pipx:httpie" = "latest"
ripgrep = "latest"
rust = "latest"
tree-sitter = "latest"
"github:dalance/procs" = "latest"
"github:peteretelej/tree" = "latest"
upt = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
yq = "latest"
zellij = "latest"
zoxide = "latest"
"cargo:diffutils" = "latest"
xh = "latest"
"github:tstack/lnav" = "latest"
"cargo:tlrc" = "latest"
carapace = "latest"
"github:ghetzel/mdnstool" = "latest"
pitchfork = "latest"
"cargo:somo" = "latest"
cosign = "latest"
opencode = "latest"
codebuff = "latest"
jjui = "latest"
jj = "latest"
"github:eza-community/eza" = "latest"
lazyssh = "latest"
"cargo:lazyjj" = "latest"
pandoc = "latest"
amp = "latest"
"npm:ctx7" = "latest"
"conda:dos2unix" = "7.5.2"
"conda:dash" = "latest"
"conda:xsel" = "latest"
"conda:rsync" = "latest"
"conda:grep" = "latest"
"conda:sed" = "latest"
"conda:dateutils" = "latest"
"conda:tzdata" = "latest"
"conda:xclip" = "latest"
"conda:resvg" = "latest"
"npm:skills" = "latest"
atuin = "latest"
"npm:playbooks" = "latest"
"devbox:imagemagick" = "latest"
python = "latest"
sd = "latest"
tmux = "latest"
aube = "latest"
fnox = "latest"
age = "latest"
