#!/usr/bin/env bash
#MISE description="Clean up Nix packages and garbage collection"

echo '[dotfiles] Starting cleanup...'

echo '[dotfiles] Deleting old generations...'
nix-collect-garbage -d
nix profile wipe-history --extra-experimental-features nix-command

echo '[dotfiles] Verifying and cleaning the store...'
nix store gc --extra-experimental-features nix-command

echo '[dotfiles] Deleting stale logs...'
sudo rm -rf /nix/var/log/nix/drvs

echo '[dotfiles] Cleanup complete'
