[tools]
"nix:dos2unix" = "latest"
"nix:gawk" = "latest"
"nix:git" = "latest"
"nix:tmux" = "latest"
"nix:xsel" = "latest"
"nix:rsync" = "latest"
"nix:rcs" = "latest"
"nix:gnugrep" = "latest"
"nix:gnused" = "latest"
"nix:dateutils" = "latest"
"nix:tzdata" = "latest"
"nix:file" = "latest"
"nix:xclip" = "latest"
"nix:wl-clipboard" = "latest"
"nix:exiftool" = "latest"
"nix:htop" = "latest"
"nix:taskwarrior-tui" = "latest"
"nix:taskwarrior" = "latest"
"nix:timewarrior" = "latest"
"nix:gnupg" = "latest"
"nix:gpg-tui" = "latest"
"nix:dash" = "latest"
"nix:amazon-q-cli" = "latest"
"nix:imagemagick" = "latest"
"nix:renameutils" = "latest"
"nix:readline" = "latest"
