[note]
default-title = "Untitled"
filename = "{{id}}"
extension = "md"
template = "default.md"
id-charset = "hex"
id-length = 8

[extra]

[group.journal.note]
filename = '{{format-date now "%Y-%m-%d_%H-%M-%S"}}'
template = "journal.md"

[format.markdown]
link-format = "[[{{filename}}{{#if title}}|{{title}}{{/if}}]]"
hashtags = true
colon-tags = false
multiword-tags = false

[tool]

[lsp]

[lsp.diagnostics]
dead-link = "error"

[lsp.completion]

[filter]

[alias]
journal = 'zk new "$ZK_NOTEBOOK_DIR/journal" "$@"'
j = 'zk journal "$@"'
