[note]
default-title = "Untitled"
filename = "{{slug title}}"
extension = "md"
template = "default.md"
id-charset = "hex"
id-length = 8

[extra]

[group.journal.note]
filename = '{{format-date now "%Y-%m-%d_%H-%M-%S"}}'
template = "journal.md"

[group.archive.note]
filename = "{{id}}"
template = "note.md"

[format.markdown]
link-format = "[[{{filename}}{{#if title}}|{{title}}{{/if}}]]"
hashtags = true
colon-tags = false
multiword-tags = false

[tool]

[lsp]

[lsp.diagnostics]
dead-link = "error"

[lsp.completion]

[filter]

[alias]
# Place cursor at EOF and start in insert mode
new = 'VISUAL="$VISUAL +$ -c startinsert" zk new "$@"'
edlast = "zk edit --limit 1 --sort modified- $@"

journal = 'zk new "$ZK_NOTEBOOK_DIR/journal" "$@"'
j = 'zk journal "$@"'
n = 'zk new "$ZK_NOTEBOOK_DIR/archive" "$@"'
