#!/usr/bin/env bash
#MISE description="Update all tools and packages"

mise run chezmoi:update
mise run devbox:self-update

if command -v brew >/dev/null; then
    mise run brew:self-update
    mise run brew:update
fi

mise run mise:update
mise run devbox:update
mise run yazi:update
mise run nvim:update
